# Supabase Configuration
project_id = "skzirkhzwhyqmnfyytcl"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge_functions]
enabled = true
port = 54326

[auth]
enabled = true
port = 54327

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = true
client_id = "your-google-client-id"
secret = "your-google-client-secret"

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.sms]
enable_signup = false

[realtime]
enabled = true

[functions.create-match-from-challenge]
verify_jwt = true

[functions.register-tournament]
verify_jwt = true

[functions.update-match-result]
verify_jwt = true

[functions.update-leaderboards]
verify_jwt = false

[functions.send-notifications]
verify_jwt = true